services:
  mssql-server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - "mssql-server:/var/opt/mssql"


  # Servizio UserService
  userservice:
    build:
      context: ./UserService
      dockerfile: Userservice.Api/Dockerfile
    container_name: userservice
    depends_on:
      - mssql-server  # 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"

 

  # Servizio BookingService
  
  bookingservice:
    build:
      context: ./BookingService
      dockerfile: BookingService.Api/Dockerfile
    container_name: bookingservice
    depends_on:
      - mssql-server  # 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:5001"

 
volumes:
  mssql-server: